# Site settings
title: JHelioviewer
suppportEmail: "support@jhelioviewer.org"
danielEmail: "daniel.mueller@esa.int"
gitPage: "https://github.com/Helioviewer-Project/JHelioviewer"
gitIssuePage: "https://github.com/Helioviewer-Project/JHelioviewer/issues" 
esaPage: "http://www.esa.int/ESA"
SDOPage: "http://sdo.gsfc.nasa.gov/"
SOHOPage: "http://sohowww.nascom.nasa.gov/"
TutorialPage: "https://www.youtube.com/watch?v=xzSV94LfRwc"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Helioviewer
github_username:  jekyll




# Build settings
markdown: kramdown
